name: OWASP ZAP Scan

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest available Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Test
        run: |
          npm install
          npm test

      - name: OWASP ZAP Scan
        run: |
          # Pull the OWASP ZAP Docker image
          docker pull owasp/zap2docker-stable

          # Run the OWASP ZAP scan in a Docker container
          docker run -v $PWD:/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t http://your-webapp-url -g gen.conf -r zap-report.html

      - name: Publish OWASP ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: zap-report.html
